package project.UI;

import javax.swing.JComboBox;

import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author nirguberman
 */
public class AutoComplete extends JComboBox {

        /**
         * Creates new form AutoComplete
         */
        String[] options;

        public AutoComplete(String[] options) {
                this.options = options;
                this.setModel(
                                new javax.swing.DefaultComboBoxModel<>(this.options));
                AutoCompleteDecorator.decorate(this);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

}